#### IBU - Test
-----------

In [3]:
import numpy as np
from bgunfolding.ibu import IBU

In [4]:
A = np.array([[0.8, 0.2],
              [0.2, 0.8]])

f = np.array([2, 2])
b = np.array([1, 2])

g = A @ f + b
g

array([3., 4.])

In [9]:
ibu = IBU(n_iterations = 1,
          x0 = np.array([3, 3]),
          epsilon = 1e-18)

ibu.fit(f, g, b, A)

In [10]:
ibu.predict()

(array([2.28, 2.37]), 1)

In [15]:
from bgunfolding.ibu import IBU

ibu = IBU(n_iterations = 1,
          x0 = np.array([3, 3]),
          epsilon = 1e-18)

ibu.fit(f = np.array([2, 2]),
        g = np.array([3, 4]),
        b = np.array([1, 2]),
        A = np.array([[0.8, 0.2],
                      [0.2, 0.8]]))

ibu.predict()[0] == np.allclose(np.array([2.28, 2.37])

array([False, False])

In [16]:
ibu.predict()[0]

array([2.28, 2.37])

In [17]:
np.isclose(ibu.predict()[0], np.array([2.28, 2.37]))

array([ True,  True])

In [70]:
dataDict = {'meta': {'n_bins_true': 12},
            'data': {'g': np.array([12, 2])}}


In [71]:
import msgpack
import msgpack_numpy as m
m.patch()

In [91]:
fp = 'test_file.json'

binary = msgpack.packb(dataDict, use_bin_type  = True)
with open(fp, 'wb') as f:
    f.write(binary)

In [96]:
with open(fp, 'rb') as f:
    rec = msgpack.unpackb(f.read(), encoding = 'utf-8')

In [97]:
from bgunfolding import sampler

In [99]:
class Test():
    def __init__(self):
        pass
    


test = {'f': np.array([1,2,3]),
        'g': np.array([1,2,3])}

### SVD Tests
---